In [4]:
import tensorflow as tf
print(tf.__version__)
import random

2.3.0


In [7]:
num_inputs = 2
num_examples = 1000

true_w = [2, -3.4]
true_b = 4.2

features = tf.random.normal((num_examples, num_inputs), stddev = 1)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b

noise = tf.random.normal(labels.shape, stddev = 0.01)

labels += noise

In [8]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        j = indices[i:min(i+batch_size, num_examples)]
        yield tf.gather(features, axis = 0, indices = j), tf.gather(labels, axis = 0, indices = j)

In [9]:
w = tf.Variable(tf.random.normal((num_inputs, 1), stddev = 0.01))
b = tf.Variable(tf.zeros(1,))

In [10]:
print(features.shape)
print(w.shape)

(1000, 2)
(2, 1)


In [11]:
def linreg(X, w, b):
    return tf.matmul(X, w) + b

In [17]:
def squared_loss(y_hat, y):
    return (y_hat - tf.reshape(y, y_hat.shape)) ** 2 / 2

In [18]:
def sgd(params, lr, batch_size, grads):
    for i, param in enumerate(params):
        param.assign_sub(lr * grads[i] / batch_size)

In [20]:
lr = 0.03
num_epochs = 3
net = linreg
loss = squared_loss
batch_size = 10
for epoch in range(num_epochs):
    for X, y in data_iter(batch_size, features, labels):
        with tf.GradientTape() as t:
            t.watch([w,b])
            l = tf.reduce_sum(loss(net(X, w, b), y))
        grads = t.gradient(l, [w, b])
        print(grads)
        sgd([w, b], lr, batch_size, grads)
    train_l = loss(net(features, w, b), labels)
    print('epoch %d, loss %f' % (epoch + 1, tf.reduce_mean(train_l)))

[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.00465878],
       [ 0.09166344]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05617452], dtype=float32)>]
[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.0322741],
       [-0.0004887]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.01523674], dtype=float32)>]
[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.01870516],
       [0.01245659]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00038093], dtype=float32)>]
[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 0.01559178],
       [-0.02119067]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00542709], dtype=float32)>]
[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.05683247],
       [0.02216854]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.02471626], dtype=float32)>]
[<tf.Tensor: shape=(2, 1), dtype=float32

[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 0.01635633],
       [-0.03176893]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.02744594], dtype=float32)>]
[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.02822987],
       [0.08557557]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.01216817], dtype=float32)>]
[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.01459107],
       [0.01010459]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.01526731], dtype=float32)>]
[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 0.01490003],
       [-0.02561047]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.02486199], dtype=float32)>]
[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 0.04154341],
       [-0.05175598]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.02769494], dtype=float32)>]
[<tf.Tensor: shape=(2, 1), dtype=floa